config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true

  scope :newest_reviews, -> { order(created_at: :desc).limit(3)}
  scope :pop_reviewed, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}

    scope :country_of_origin, -> (country_of_origin_parameter) { where(country_of_origin: "USSR") }
    scope :usa_made_product, -> { where(country_of_origin: "USA") }
    before_save(:titleize_product)

    private
    def titleize_product
      self.name = self.name.titleize
    end
  end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true, length: { minimum: 50, maximum: 250 }
  validates :rating, presence: true
  validates :rating,  inclusion: 1..5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :confirgure_permitted_parameters, if: :devise_controller?

  protected

  def confirgure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:admin, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:admin, :email, :password, :current_password) }
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @product = Product.all
    render :index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]


  def index
    @product = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new  end

  def create
    @product = Product.new(product_params)
      if @product.save
        flash[:notice] = "Product added!"

        redirect_to products_path
      else
        flash[:alert] = "Product not added, try again."
        render :new
      end
    end

  def show
      @product = Product.find(params[:id])
      render :show
  end

  def edit
      @product = Product.find(params[:id])
      render :edit
  end

  def update
      @product= Product.find(params[:id])
      if @product.update(product_params)
        flash[:notice] = "Product updated!"
        redirect_to products_path
    else
        render :edit
    end
  end

  def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_path
  end
    private
  def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  
  before_action :authenticate_user!, except: [:show, :index]
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)

    if @review.save
      flash[:notice] = "Review added!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Review not added."
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end
  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review updated!"
      redirect_to product_path(@review.product)
    else
      flash[:notice] = "Review not updated."
      render :edit
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>MARIO'S</h1>
<h3 id="fine">Fine Foods Provided with a Smile!</h3>
<h4><i>Contact Information</i></h4>
<ul>
  <li>Telephone: 123-456-7891</li>
  <li>Email: mario@foods.com</li>
  <li>Address: 1234 Main St.</li>
</ul>

<h4>What people are talking about most:</h4>

<% if @product.any? %>
<ul>
  <% @product.pop_reviewed.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no products yet.</p>
<% end %>

<h4>Our newest products:</h4>

<% if @product.any? %>
<ul>
  <% @product.newest_reviews.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% end %>
<br>


<h4>Products made in the USA:</h4>

<% if @product.any? %>
<ul>
  <% @product.usa_made_product.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no products made in the United States yet.</p>
<% end %>


<p><%= link_to "Create new product", new_product_path %></p>
<p><%= link_to "Current Products", products_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3><span>Please fix these errors:</span></h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><span><%= message %></span></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MariosAuth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if current_user %>
      <p id="user-email"><%= current_user.email %></p>
      <p id="sign-out"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></p>
      <% else %>
      <p id="sign-up"><%= link_to "Sign Up", new_user_registration_path %></p>
      <p id="sign-in"><%= link_to "Sign In", new_user_session_path %></p>
      <% end %>
      <%= flash[:alert] %>
      <%= flash[:notice] %>

  <%= flash[:alert] %>
  <%= flash[:notice] %>

  <p> <%= link_to "Home", root_path %> </p>

  <%= yield %>
</body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= form_for @product do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :cost %>
<%= f.number_field :cost, step: :any %>
<%= f.label :country_of_origin %>
<%= f.text_field :country_of_origin %>
<%= f.submit  %>

<% end %>

app/views/products/index.html.erb
<h1>MARIO'S</h1>

<h4>Current Inventory</h4>

<% if @product.any? %>
<ul>
  <% @product.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no products yet.</p>
<% end %>
<br>


<% if current_user && current_user.admin %>
<p><%= link_to "Create new product", new_product_path %></p>
<% end %>


<p><%= link_to "Return to products", products_path %></p>

app/views/products/new.html.erb
<h1>Add a new product:</h1>

<%= form_for @product do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :cost %>
<%= f.number_field :cost, step: :any %>
<%= f.label :country_of_origin %>
<%= f.text_field :country_of_origin %>
<%= f.submit  %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h4><%= @product.country_of_origin %></h4>
<h4>$<%= @product.cost %></h4>

<% if @product.reviews.any? %>
  <h4>Reviews for this product:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews listed for this product.</p>
<% end %>

<% if current_user %>
<p><%= link_to "Add a review", new_product_review_path(@product) %></p>
<% end %>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete product", product_path(@product),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit review:</h1>

<%= form_for [@product, @review] do |f| %>
<%= f.label :author %>
<%= f.text_field :author %>
<%= f.label :content_body %>
<%= f.text_area :content_body %>
<%= f.label :rating %>
<%= f.number_field :rating %>
<p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a new review:</h1>

<%= form_for [@product, @review] do |f| %>
<%= f.label :author %>
<%= f.text_field :author %>
<%= f.label :content_body %>
<%= f.text_area :content_body %>
<%= f.label :rating %>
<%= f.number_field :rating %>
<p><%= f.submit %></p>
<% end %>

app/views/reviews/show.html.erb
<h1>Product: <%= @product.name %></h1>

<h2>By: <%= @review.author %></h2>
<h3>Rating: <%= @review.rating %></h3>
<h4>Review: <%= @review.content_body %></h4>
<% if current_user && current_user.admin %>
<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                      :data => {:confirm => "Are you sure?",
                                     :method => "delete"} %></p>
<% end %>


<p><%= link_to "Return to product", product_path(@product) %></p>